name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.5.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        tools: 'tools_cmake'
    
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v1.3
    
    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
    
    - name: Build
      run: cmake --build build --config Release
    
    - name: Deploy Qt
      run: |
        cd build/Release
        windeployqt.exe GameBird.exe --qmldir ../../qml --release
    
    - name: Install Inno Setup
      run: |
        choco install innosetup -y
    
    - name: Update Installer Script
      run: |
        (Get-Content installer.iss) -replace 'build\\', 'build/Release/' | Set-Content installer.iss
    
    - name: Create Installer
      run: |
        & "C:\Program Files (x86)\Inno Setup 6\iscc.exe" installer.iss
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Output/GameBird-*.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}